apiVersion: v1
kind: Service
metadata:
  name: spaceland-front-lb
spec:
  type: LoadBalancer
  selector:
    app: spaceland-front
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443


