apiVersion: v1
kind: Service
metadata:
  name: spaceland-front-svc
  labels:
    app: spaceland-front
spec:
  type: ClusterIP
  selector:
    app: spaceland-front
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
